import { IndustryConfig } from '@/core/registry/industryRegistry';

export const gymConfig: IndustryConfig = {
  id: 'gym',
  name: 'Gym',
  slug: 'gym',
  description: 'Members + Attendance',
  icon: 'Dumbbell',
  theme: {
    primary: '#FF6B35',
    secondary: '#FF8C42',
    accent: '#FFE5D9',
    background: '#FFF5F0',
  },
  modules: [
    'dashboard',
    'members',
    'memberships',
    'plans',
    'trainers',
    'attendance',
    'appointments',
    'payments',
    'expenses',
    'classes',
    'subscriptions',
    'reports',
    'crm',
    'ai-advisor',
    'notifications',
    'settings',
  ],
  dashboardWidgets: [
    'active-members',
    'new-members',
    'expiring-memberships',
    'todays-attendance',
    'monthly-revenue',
    'outstanding-payments',
    'trainer-performance',
    'popular-plans',
    'member-retention',
    'churn-rate',
  ],
  features: {
    inventory: false,
    sales: false,
    purchases: false,
    customers: true,
    suppliers: false,
    billing: true,
    tax: true,
    gst: false,
    reports: true,
    ai: true,
    appointments: true,
    memberships: true,
    kitchen: false,
    tables: false,
  },
};
