import { IndustryConfig } from '@/core/registry/industryRegistry';

export const multigrainConfig: IndustryConfig = {
  id: 'multigrain-store',
  name: 'Multigrain Store',
  slug: 'multigrain-store',
  description: 'Inventory + Billing',
  icon: 'Grain',
  theme: {
    primary: '#8B6914',
    secondary: '#D4A84B',
    accent: '#F5E6C8',
    background: '#FDF8F0',
  },
  modules: [
    'dashboard',
    'sales',
    'outward-orders',
    'billing',
    'inventory',
    'inward',
    'stock-movement',
    'returns',
    'customers',
    'suppliers',
    'finance',
    'expenses',
    'reports',
    'custom-reports',
    'tax',
    'itr',
    'ai-advisor',
    'notifications',
    'settings',
  ],
  dashboardWidgets: [
    'todays-sales',
    'todays-orders',
    'gross-profit',
    'expenses',
    'estimated-profit',
    'stock-value',
    'low-stock',
    'outstanding-payments',
    'best-sellers',
    'slow-moving',
    'sales-trend',
    'profit-trend',
    'ai-recommendations',
  ],
  features: {
    inventory: true,
    sales: true,
    purchases: true,
    customers: true,
    suppliers: true,
    billing: true,
    tax: true,
    gst: true,
    reports: true,
    ai: true,
    appointments: false,
    memberships: false,
    kitchen: false,
    tables: false,
  },
};
